### ISSUE TITLE
Extensions working upon install, and then not

### ISSUE THREAD

**Issue by michel-m** [ungoogled-software/ungoogled-chromium-android#48] opened 2021-01-18 15:10 UTC
Please at least answer all questions marked with * below. Issues without answering these questions will be closed.

**\*Device info (please complete the following information):**
 - Device: OnePlus 3 (3003)
 - OS: OxygenOS 9.0.6
 - Arch: arm64
 - Variant: N/A
 - Version: 87.0.4280.141
 
**\*Is the bug related to extensions?**
Yes

**\*If not related to extensions, can the bug be reproduced with corresponding Chromium version?**
Yes/No

**\*Describe the bug**
Upon install of extensions (I have only tried uBlock origin and HTTPS everywhere), they work perfectly well, and then if I close the browser and open it again they don't work anymore. If I reinstall them they work, but will stop working if I close the browser and reopen it.

**\*To Reproduce**
1. Install uBlock origin
2. Search Startpage for "iPhone", for example
3. No ads shown
4. Close browser, open it again
5. Search Startpage for "iPhone"
6. Ads are shown (even though uBlock origin does still appear in chrome://extensions, and its settings pages are perfectly accessible)

**\*Expected behavior**
Extensions should work all the time once installed.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by wchen342** [comment] 2021-01-18 19:01
Can confirm. Seems to have something to do with tabs.

**Comment by wchen342** [comment] 2021-01-21 19:34
Temporarily fixed in bbae620 until a better way is found. There is a minor bug that the first time you switch back and the tab got reloaded then medias will not display. A refresh will solve it.

**Comment by michel-m** [comment] 2021-01-21 19:39
Thanks for letting me know! I'll let you decide whether to keep this issue open or not.

**Comment by wchen342** [comment] 2021-01-21 19:42
I will keep it open but don't expect it to be fully fixed any time soon. The underlying issue is quite complicated and I doubt it can be fixed without a rewrite of some core startup logics.

**Comment by michel-m** [comment] 2021-01-26 19:19
Tested, works perfectly, thank you very much! (Extensions don't seem to work in incognito tabs though, not sure if that's expected – it's a minor issue though.)

**Comment by chiffon-rouge** [comment] 2021-01-26 19:22
Can confirm as well. Thank you!

> (Extensions don't seem to work in incognito tabs though, not sure if that's expected – it's a minor issue though.)

Isn't that by design, though?

**Comment by wchen342** [comment] 2021-01-26 20:02
Extensions are supposed to work in incognito tabs if you check an option (I think it's in the extension page), but I haven't implement that yet since I want to see whether it works on normal pages first.

**Comment by Balachandarsmr** [comment] 2021-01-29 08:25
Switched from Firefox. Ublock origin working fine. Thanks for your great effort.

**Closed** 2021-03-03 18:42 UTC
Labels: bug, extensions
