### ISSUE TITLE
[BUG] Application crash

### ISSUE THREAD

**Issue by wanlyg** [ungoogled-software/ungoogled-chromium-android#61] opened 2021-02-17 12:19 UTC
Please at least answer all questions marked with * below. Issues without answering these questions will be closed.

**\*Device info (please complete the following information):**
 - Device: xiaomi mi6
 - OS: LineageOS 18.1 (Android 11)
 - Arch: arm64
 - Variant: Extensions
 - Version: v88.0.4324.152-2
 
**\*Is the bug related to extensions?**
Yes

**\*If not related to extensions, can the bug be reproduced with corresponding Chromium version?**
Yes/No

**\*Describe the bug**
①. When installing the [avira](https://chrome.google.com/webstore/detail/avira-password-manager/caljgklbbfbcjjanaijlacgncafpegll)  plugin, the app crashes
②. When [Violentmonkey](https://chrome.google.com/webstore/detail/violentmonkey/jinjaccalgkegednnccohejagnlnfdag)  is enabled, close tab crashes

**\*To Reproduce**
for ①,  1.Only need to install [avira](https://chrome.google.com/webstore/detail/avira-password-manager/caljgklbbfbcjjanaijlacgncafpegll) .
for ②,  1.Install [Violentmonkey](https://chrome.google.com/webstore/detail/violentmonkey/jinjaccalgkegednnccohejagnlnfdag)
           2.Click to view all tabs
           3.Close a tab

**\*Expected behavior**
Fix bug

**Screenshots**
No
**Additional context**

Thank you very much for your work

**Comment by wchen342** [comment] 2021-02-17 12:46
(2) seems to be the same with #59. I cannot reproduce it on `-3`. Please try when the version is released.

(1) is a different bug. I will fix it in next version.

**Comment by hbarsaiyan** [comment] 2021-02-17 13:11
arm64 extension variant crashes on video playback in sites like Twitter (YouTube works fine though). I have no extensions installed. arm variant plays the video fine though. I have attatched the log below.
[Log_2021-02-17_18-35-36.txt](https://github.com/ungoogled-software/ungoogled-chromium-android/files/5995836/Log_2021-02-17_18-35-36.txt)

Apart from that the crash on closing tabs seems to be fixed 🎉. Thank you.

**Comment by wchen342** [comment] 2021-02-17 13:12
@hbarsaiyan Does it happen with non-extension-support version?

**Comment by hbarsaiyan** [comment] 2021-02-17 13:19
@wchen342 yes I can confirm it's happening on the non-extension arm64 variant also.

**Comment by wanlyg** [comment] 2021-02-17 13:21
Confirmed that issue ② has been fixed in v88.0.4324.152-3 
@wchen342

**Comment by wchen342** [comment] 2021-02-17 13:24
I think it is the GPU accleration on specific hardware. I remember Bromite used to have the same problem and I cannot reproduce on emulator or my Sony phone.

I will grab the bromite patch and compile a debug build for you to test.

**Comment by hbarsaiyan** [comment] 2021-02-17 13:36
> @hbarsaiyan I think it is the GPU accleration on specific hardware. I remember Bromite used to have the same problem and I cannot reproduce on emulator or my Sony phone.
> 
> I will grab the bromite patch and compile a debug build for you to test.

OK thank you very much.

**Comment by wchen342** [comment] 2021-02-18 00:39
@hbarsaiyan Please try [this apk](https://uc.droidware.info/tmp/ChromeModernPublic.apk) and see whether it still crashes.

**Comment by NSTAdventure** [comment] 2021-02-18 02:20
> (2) seems to be the same as #59. I cannot reproduce it on `-3`. Please try when the version is released.
> 
> (1) is a different bug. I will fix it in next version.
> 
> EDIT: the release is out now.

Hey did https everywhere work for you? I can't test it :-(

**Comment by hbarsaiyan** [comment] 2021-02-18 05:48
> @hbarsaiyan Please try [this apk](https://uc.droidware.info/tmp/ChromeModernPublic.apk) and see whether it still crashes.

Sadly no, it still crashes. I had some other people also report the same bug.
![IMG_20210217_190000](https://user-images.githubusercontent.com/37732050/108311242-bd706100-71da-11eb-841e-d58bdb08cf39.jpg)

> > (2) seems to be the same as #59. I cannot reproduce it on `-3`. Please try when the version is released.
> > (1) is a different bug. I will fix it in next version.
> > EDIT: the release is out now.
> 
> Hey did https everywhere work for you? I can't test it :-(

Yes https everywhere is working fine.

**Comment by wchen342** [comment] 2021-02-18 09:45
@hbarsaiyan Can you check whether the flag `enable-image-reader` is disabled?
Also post the log please. The apk is a debug build so the output should tell where the crash happens.

**Comment by wchen342** [comment] 2021-02-18 10:10
Wrong file indeed. Can you try again? [The link](https://uc.droidware.info/tmp/ChromeModernPublic.apk) is the same.

**Comment by hbarsaiyan** [comment] 2021-02-18 10:43
> Wrong file indeed. Can you try again? [The link](https://uc.droidware.info/tmp/ChromeModernPublic.apk) is the same.

Disabling `enable-image-reader` fixed the problem 🎉 Strangely I had enabled it when I was on the arm32 extension build, but it does not work on arm64 variant. I then set it to default but that also did not work so I believe it is enabled by default on android P+ devices. BTW the build you sent also has the tab crash problem. I have attached the log below. Thank you.
[Log_2021-02-18_16-10-35.txt](https://github.com/ungoogled-software/ungoogled-chromium-android/files/6002165/Log_2021-02-18_16-10-35.txt)

**Comment by wchen342** [comment] 2021-02-18 10:46
> BTW the build you sent also has the tab crash problem

You mean the previous one? Because the later one should be a non-extension build.

> I had enabled it when I was on the arm32 extension build, but it does not work on arm64 variant.

This is a specific problem with arm64, so only on some arm64 devices you need to disable that flag.

**Comment by hbarsaiyan** [comment] 2021-02-18 10:48
> > BTW the build you sent also has the tab crash problem
> 
> You mean the previous one? Because the later one should be a non-extension build.
> 
> > I had enabled it when I was on the arm32 extension build, but it does not work on arm64 variant.
> 
> This is a specific problem with arm64, so only on some arm64 devices you need to disable that flag.

But the package name on the second build you sent is `org.ungoogled.chromium.extensions.stable` 🤔

**Comment by wchen342** [comment] 2021-02-18 10:52
Oh I think I knew what was going on. It was the CDN's cache..

Anyway since now I know the flag fixes the problem I will just include the patch in next release.

**Comment by wchen342** [comment] 2021-02-18 23:45
Patch is included in `.182`.

**Closed by wchen342** 2021-02-18 23:45 UTC
Labels: bug, extensions

**Comment by wchen342** [comment] 2021-02-18 23:48
I haven't been able to figure out how the extension opens new tab. Some information from the extension developer will be helpful.

**Comment by wanlyg** [comment] 2021-02-19 00:17
I cannot help you. But I need to point out that avira will create a new privacy window.
The avira pop-up window sometimes does not work in the kiwi browser, but you can pop up the window by checking the desktop version of the webpage. even if you return to uncheck the desktop version.
I can't test the computer version of Chrome, it may be a plug-in bug.
@wchen342

**Comment by wchen342** [comment] 2021-02-19 00:21
I tested it on desktop and it doesn't seem to open incognito window? I saw it open a normal tab.
@kiwibrowser Do you remember how you made this work?

**Comment by wchen342** [comment] 2021-02-19 00:38
Discussion moved to #66.
