### ISSUE TITLE
Extensions listed in menu

### ISSUE THREAD

**Issue by androidacy** [ungoogled-software/ungoogled-chromium-android#21] opened 2020-06-24 03:33 UTC
**Please explain why your feature request fall into the scope of ungoogled-chromium?**
See [ungoogled-chromium#objectives](https://github.com/Eloston/ungoogled-chromium#objectives) for a detailed list of objectives of this project. 

I'm not sure it's specifically in scope but definitely not out of scope.

**Please describe the feature you would like to have**
A clear and concise description of what the problem is. 

Not all extensions have an options link in chrome://extensions. Rather they depend on the toolbar menu for configuration. See: Dark Reader

**Describe the solution you'd like**
Extensions show up in menu

**Describe alternatives you've considered**
Really there isn't one. On mobile there is no other good place to put the extension icons, and as stated some extensions rely on the toolbar menu for configuration

**Additional context**

**Comment by wchen342** [comment] 2020-06-24 03:35
Duplicate of [https://git.droidware.info/wchen342/ungoogled-chromium-android/issues/33](https://git.droidware.info/wchen342/ungoogled-chromium-android/issues/33) but I will keep it here for convenience.

**Comment by linuxandria** [comment] 2020-06-24 03:36
We already know my thoughts on gitea :)

Thanks

**Comment by wchen342** [comment] 2020-06-24 03:41
i am only doing this for old issues before the migration but not for future ones.your

Also I still don't know how that happened to you. I assume your IME is not in en_US?

**Comment by linuxandria** [comment] 2020-06-24 03:43
> I am only doing this for old issues before the migration but not for future ones.
> 
> Also I still don't know how that happened to you. I assume your IME is not in en_US?

No, it's en-US

**Comment by wchen342** [comment] 2020-06-24 03:46
Weird, I will investigate myself. This is off topic though so I'm going to fold this part.

**Comment by linuxandria** [comment] 2020-06-24 03:46
> I am only doing this for old issues before the migration but not for future ones.
> 
> Also I still don't know how that happened to you. I assume your IME is not in en_US?

It's getting late but I'll try GitNex for Android tomorrow, hopefully I'll have better luck with it

**Comment by wchen342** [comment] 2021-02-15 03:17
Added in 7cef1fe.

**Closed by wchen342** 2021-02-15 03:17 UTC
Labels: extensions
