### ISSUE TITLE
Crash on toggling dark mode

### ISSUE THREAD

**Issue by neodada** [ungoogled-software/ungoogled-chromium-android#74] opened 2021-02-23 02:45 UTC
Please at least answer all questions marked with * below. Issues without answering these questions will be closed.

**\*Device info (please complete the following information):**
 - Device: Redmi Note 9 Pro Max
 - OS: MIUI 12 Android 10
 - Arch: arm64
 - Variant: no idea
 - Version: 88.0.4324.152
 
**\*Is the bug related to extensions?**
No

**\*If not related to extensions, can the bug be reproduced with corresponding Chromium version?**
No

**\*Describe the bug**
On toggling MIUI's dark mode app crashes

**\*To Reproduce**
Just toggle dark mode in MIUI

**\*Expected behavior**
UI should change according to MIUI dark mode

**Screenshots**

**Additional context**
Bug report

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Redmi/joyeuse_global/joyeuse:10/QKQ1.191215.002/V11.0.5.0.QJZMIXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2021-02-23 07:59:18+0530
pid: 30259, tid: 30259, name: tensions.stable  >>> org.ungoogled.chromium.extensions.stable <<<
uid: 10542
signal 5 (SIGTRAP), code -6 (SI_TKILL), fault addr --------
    x0  0000007c4dfee050  x1  0000007fd69b1b50  x2  0000000000000000  x3  0000000000000002
    x4  0000000000000004  x5  0000000000000000  x6  0000007d3efa7000  x7  0000000005f00c74
    x8  0000000000000001  x9  000000000133f96a  x10 0000000000000000  x11 20c49ba5e353f7cf
    x12 00000088cc0daac0  x13 fffffffffc000000  x14 0000000000000040  x15 0000000000000040
    x16 0000007c4a466430  x17 0000007d3c113a88  x18 0000007d3ec0e000  x19 00000088cc1012b2
    x20 0000007c4a477000  x21 0000007c4aa31000  x22 0000000012f913b8  x23 00000000a1e2d1f8
    x24 0000000000000004  x25 0000007d3dd18020  x26 0000007d3db630b0  x27 0000000000000043
    x28 0000007d3dd18020  x29 0000007fd69b1b50
    sp  0000007fd69b1b20  lr  0000007c48a2bb34  pc  0000007c47489b50

backtrace:
      #00 pc 0000000003587b50  /data/app/org.ungoogled.chromium.extensions.stable-wE7jS1moCi1KdGs7PnStvg==/base.apk!libchrome.so (offset 0x1e6a000) (BuildId: ad5980690310f9c0969f4e6afb9e41923fb5f08a)
      #01 pc 0000000004b29b30  /data/app/org.ungoogled.chromium.extensions.stable-wE7jS1moCi1KdGs7PnStvg==/base.apk!libchrome.so (offset 0x1e6a000) (BuildId: ad5980690310f9c0969f4e6afb9e41923fb5f08a)
      #02 pc 00000000000d0070  /data/app/org.ungoogled.chromium.extensions.stable-wE7jS1moCi1KdGs7PnStvg==/oat/arm64/base.odex (art_jni_trampoline+144)
      #03 pc 00000000001bccac  /data/app/org.ungoogled.chromium.extensions.stable-wE7jS1moCi1KdGs7PnStvg==/oat/arm64/base.odex (zz.run+268)
      #04 pc 0000000000137334  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: 8decd6ee169e57b0ad19b2e9f38538de)
      #05 pc 0000000000145fec  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+244) (BuildId: 8decd6ee169e57b0ad19b2e9f38538de)
      #06 pc 00000000004b0dc8  /apex/com.android.runtime/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104) (BuildId: 8decd6ee169e57b0ad19b2e9f38538de)
      #07 pc 00000000004b2214  /apex/com.android.runtime/lib64/libart.so (art::InvokeVirtualOrInterfaceWithVarArgs(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+424) (BuildId: 8decd6ee169e57b0ad19b2e9f38538de)
      #08 pc 0000000000398220  /apex/com.android.runtime/lib64/libart.so (art::JNI::CallVoidMethodV(_JNIEnv*, _jobject*, _jmethodID*, std::__va_list)+628) (BuildId: 8decd6ee169e57b0ad19b2e9f38538de)
      #09 pc 0000000001fb7928  /data/app/org.ungoogled.chromium.extensions.stable-wE7jS1moCi1KdGs7PnStvg==/base.apk!libchrome.so (offset 0x1e6a000) (BuildId: ad5980690310f9c0969f4e6afb9e41923fb5f08a)
      #10 pc 00000000035f234c  /data/app/org.ungoogled.chromium.extensions.stable-wE7jS1moCi1KdGs7PnStvg==/base.apk!libchrome.so (offset 0x1e6a000) (BuildId: ad5980690310f9c0969f4e6afb9e41923fb5f08a)
      #11 pc 00000000035f21fc  /data/app/org.ungoogled.chromium.extensions.stable-wE7jS1moCi1KdGs7PnStvg==/base.apk!libchrome.so (offset 0x1e6a000) (BuildId: ad5980690310f9c0969f4e6afb9e41923fb5f08a)
      #12 pc 00000000035f2408  /data/app/org.ungoogled.chromium.extensions.stable-wE7jS1moCi1KdGs7PnStvg==/base.apk!libchrome.so (offset 0x1e6a000) (BuildId: ad5980690310f9c0969f4e6afb9e41923fb5f08a)
      #13 pc 00000000035a4078  /data/app/org.ungoogled.chromium.extensions.stable-wE7jS1moCi1KdGs7PnStvg==/base.apk!libchrome.so (offset 0x1e6a000) (BuildId: ad5980690310f9c0969f4e6afb9e41923fb5f08a)
      #14 pc 00000000035b3688  /data/app/org.ungoogled.chromium.extensions.stable-wE7jS1moCi1KdGs7PnStvg==/base.apk!libchrome.so (offset 0x1e6a000) (BuildId: ad5980690310f9c0969f4e6afb9e41923fb5f08a)
      #15 pc 00000000035e491c  /data/app/org.ungoogled.chromium.extensions.stable-wE7jS1moCi1KdGs7PnStvg==/base.apk!libchrome.so (offset 0x1e6a000) (BuildId: ad5980690310f9c0969f4e6afb9e41923fb5f08a)
      #16 pc 00000000035e46c8  /data/app/org.ungoogled.chromium.extensions.stable-wE7jS1moCi1KdGs7PnStvg==/base.apk!libchrome.so (offset 0x1e6a000) (BuildId: ad5980690310f9c0969f4e6afb9e41923fb5f08a)
      #17 pc 00000000000183a0  /system/lib64/libutils.so (android::Looper::pollInner(int)+832) (BuildId: 87c165c7873a550ac7eee06457668123)
      #18 pc 0000000000017fc0  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+56) (BuildId: 87c165c7873a550ac7eee06457668123)
      #19 pc 000000000013ec9c  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44) (BuildId: 6161fa476cef00d9c57060fb3e9423f7)
      #20 pc 00000000014239ec  /system/framework/arm64/boot-framework.oat (art_jni_trampoline+140) (BuildId: 254309ef4dc00693220dc284c21448a5e6c696b1)
      #21 pc 00000000016a8034  /system/framework/arm64/boot-framework.oat (android.os.MessageQueue.next+228) (BuildId: 254309ef4dc00693220dc284c21448a5e6c696b1)
      #22 pc 00000000016a34c8  /system/framework/arm64/boot-framework.oat (android.os.Looper.loop+680) (BuildId: 254309ef4dc00693220dc284c21448a5e6c696b1)
      #23 pc 0000000000cbd5d4  /system/framework/arm64/boot-framework.oat (android.app.ActivityThread.main+756) (BuildId: 254309ef4dc00693220dc284c21448a5e6c696b1)
      #24 pc 00000000001375b8  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_static_stub+568) (BuildId: 8decd6ee169e57b0ad19b2e9f38538de)
      #25 pc 000000000014600c  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+276) (BuildId: 8decd6ee169e57b0ad19b2e9f38538de)
      #26 pc 00000000004b0dc8  /apex/com.android.runtime/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104) (BuildId: 8decd6ee169e57b0ad19b2e9f38538de)
      #27 pc 00000000004b296c  /apex/com.android.runtime/lib64/libart.so (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1480) (BuildId: 8decd6ee169e57b0ad19b2e9f38538de)
      #28 pc 000000000043dc04  /apex/com.android.runtime/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+52) (BuildId: 8decd6ee169e57b0ad19b2e9f38538de)
      #29 pc 00000000006d4ea4  /system/framework/arm64/boot.oat (art_jni_trampoline+180) (BuildId: 8365d1460c1dbd1470ded083ab4a26902920da3c)
      #30 pc 0000000002322908  /system/framework/arm64/boot-framework.oat (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+136) (BuildId: 254309ef4dc00693220dc284c21448a5e6c696b1)
      #31 pc 0000000002343254  /system/framework/arm64/boot-framework.oat (com.android.internal.os.ZygoteInit.main+2100) (BuildId: 254309ef4dc00693220dc284c21448a5e6c696b1)
      #32 pc 00000000001375b8  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_static_stub+568) (BuildId: 8decd6ee169e57b0ad19b2e9f38538de)
      #33 pc 000000000014600c  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+276) (BuildId: 8decd6ee169e57b0ad19b2e9f38538de)
      #34 pc 00000000004b0dc8  /apex/com.android.runtime/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104) (BuildId: 8decd6ee169e57b0ad19b2e9f38538de)
      #35 pc 00000000004b09b8  /apex/com.android.runtime/lib64/libart.so (art::InvokeWithVarArgs(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+408) (BuildId: 8decd6ee169e57b0ad19b2e9f38538de)
      #36 pc 00000000003bb6b4  /apex/com.android.runtime/lib64/libart.so (art::JNI::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+624) (BuildId: 8decd6ee169e57b0ad19b2e9f38538de)
      #37 pc 00000000000c19ec  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+116) (BuildId: 6161fa476cef00d9c57060fb3e9423f7)
      #38 pc 00000000000c49b0  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+944) (BuildId: 6161fa476cef00d9c57060fb3e9423f7)
      #39 pc 00000000000035bc  /system/bin/app_process64 (main+1388) (BuildId: 209452f0bce09e609f3b28cd8022df9a)
      #40 pc 000000000007e898  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+108) (BuildId: 1eb18e444251dc07dff5ebd93fce105c)

**Comment by wchen342** [comment] 2021-02-23 09:48
Duplicate of #64.

**Closed by wchen342** 2021-02-23 09:48 UTC
